/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "calculate_desc_column.h"

void
calculate_desc_column_gen_class::generate_calculate_desc_column(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  if (epilogue)
    {
      stream << "column += 2 * ";
      stream << param_padding;
      stream << ";";
      stream << "\n";
      stream << indent_str;
      stream << "if( column > ";
      stream << max_desc_column;
      stream << " )";
      stream << "\n";
      stream << indent_str;
      stream << "  column = ";
      stream << max_desc_column;
      stream << ";";
      stream << "\n";
      stream << indent_str;
    }
  else
    {
      stream << "len = strlen( ";
      generate_string (array, stream, indent + indent_str.length ());
      stream << "[";
      stream << index;
      stream << "] );";
      stream << "\n";
      stream << indent_str;
      stream << "if( len > column ) column = len;";
      stream << "\n";
      stream << indent_str;
    }
}
