/*
 * File automatically generated by
 * gengen 1.1 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "file_save_multiple.h"

void
file_save_multiple_gen_class::generate_file_save_multiple(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  if (has_arg)
    {
      stream << "write_multiple_into_file(outfile, args_info->";
      generate_string (opt_var, stream, indent + indent_str.length ());
      stream << "_given, \"";
      generate_string (opt_name, stream, indent + indent_str.length ());
      stream << "\", args_info->";
      generate_string (opt_var, stream, indent + indent_str.length ());
      stream << "_orig);";
      stream << "\n";
      stream << indent_str;
    }
  else
    {
      stream << "write_multiple_into_file(outfile, args_info->";
      generate_string (opt_var, stream, indent + indent_str.length ());
      stream << "_given, \"";
      generate_string (opt_name, stream, indent + indent_str.length ());
      stream << "\", 0);";
      stream << "\n";
      stream << indent_str;
    }
}
