/*
 * File automatically generated by
 * gengen 1.0 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef FREE_INPUTS_STRING_GEN_CLASS_H
#define FREE_INPUTS_STRING_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class free_inputs_string_gen_class
{
 protected:
  string structure;

 public:
  free_inputs_string_gen_class()
  {
  }
  
  free_inputs_string_gen_class(const string &_structure) :
    structure (_structure)
  {
  }

  static void
  generate_string(const string &s, ostream &stream, unsigned int indent)
  {
    if (!indent || s.find('\n') == string::npos)
      {
        stream << s;
        return;
      }

    string::size_type pos;
    string::size_type start = 0;
    string ind (indent, ' ');
    while ( (pos=s.find('\n', start)) != string::npos)
      {
        stream << s.substr (start, (pos+1)-start);
        start = pos+1;
        if (start+1 <= s.size ())
          stream << ind;
      }
    if (start+1 <= s.size ())
      stream << s.substr (start);
  }

  void set_structure(const string &_structure)
  {
    structure = _structure;
  }

  void generate_free_inputs_string(ostream &stream, unsigned int indent = 0);
  
};

#endif // FREE_INPUTS_STRING_GEN_CLASS_H
