/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "group_option.h"

void
group_option_gen_class::generate_group_option(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  stream << "if (args_info->";
  generate_string (group_var_name, stream, indent + indent_str.length ());
  stream << "_group_counter ";
  generate_string (Comparison_rule, stream, indent + indent_str.length ());
  stream << ")";
  stream << "\n";
  stream << indent_str;
  stream << "  {";
  stream << "\n";
  stream << indent_str;
  stream << "    fprintf (stderr, dngettext (gengetopt_client_domain (),";
  stream << "\n";
  stream << indent_str;
  stream << "	\"%s%s: one option of group %$3s was given.  The number required is \"";
  stream << "\n";
  stream << indent_str;
  stream << "	  \"%$4d.\\n\",";
  stream << "\n";
  stream << indent_str;
  stream << "	\"%s%s: %$5d options of group %$3s were given.  The number required \"";
  stream << "\n";
  stream << indent_str;
  stream << "	  \"is %$4d.\\n\",";
  stream << "\n";
  stream << indent_str;
  stream << "	args_info->";
  generate_string (group_var_name, stream, indent + indent_str.length ());
  stream << "_group_counter),";
  stream << "\n";
  stream << indent_str;
  indent = 6;
  stream << "      ";
  generate_string (package_var_name, stream, indent + indent_str.length ());
  stream << ", error_location,";
  indent = 0;
  stream << "\n";
  stream << indent_str;
  stream << "      \"";
  generate_string (group_name, stream, indent + indent_str.length ());
  stream << "\", ";
  generate_string (number_required, stream, indent + indent_str.length ());
  stream << ",";
  stream << "\n";
  stream << indent_str;
  stream << "      args_info->";
  generate_string (group_var_name, stream, indent + indent_str.length ());
  stream << "_group_counter);";
  stream << "\n";
  stream << indent_str;
  stream << "    error_occurred = 1;";
  stream << "\n";
  stream << indent_str;
  stream << "  }";
  stream << "\n";
  stream << indent_str;
}
