/*
 * File automatically generated by
 * gengen 1.0 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "group_counter.h"

void
group_counter_gen_class::generate_group_counter(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  stream << "int ";
  generate_string (group_name, stream, indent + indent_str.length ());
  stream << "_group_counter; /* counter for group ";
  generate_string (group_name, stream, indent + indent_str.length ());
  stream << " */";
}
