/*
 * File automatically generated by
 * gengen 0.6 by Lorenzo Bettini 
 * http://www.lorenzobettini.it/software/gengen
 */

#include "multiple_option_update.h"

void
multiple_option_update_gen_class::generate_multiple_option_update(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  generate_string (option_var_name, stream, indent + indent_str.length ());
  stream << "_new = (struct ";
  generate_string (option_var_name, stream, indent + indent_str.length ());
  stream << "_list *) malloc (sizeof (struct ";
  generate_string (option_var_name, stream, indent + indent_str.length ());
  stream << "_list));";
  stream << "\n";
  stream << indent_str;
  generate_string (option_var_name, stream, indent + indent_str.length ());
  stream << "_new->next = ";
  generate_string (option_var_name, stream, indent + indent_str.length ());
  stream << "_list;";
  stream << "\n";
  stream << indent_str;
  generate_string (option_var_name, stream, indent + indent_str.length ());
  stream << "_list = ";
  generate_string (option_var_name, stream, indent + indent_str.length ());
  stream << "_new;";
  stream << "\n";
  stream << indent_str;
}
