/*
 * File automatically generated by
 * gengen 0.6 by Lorenzo Bettini 
 * http://www.lorenzobettini.it/software/gengen
 */

#include "print_help_string.h"

void
print_help_string_gen_class::generate_print_help_string(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  stream << "printf(\"%s\\n\",\"";
  generate_string (helpstring, stream, indent + indent_str.length ());
  stream << "\");";
  stream << "\n";
  stream << indent_str;
}
