/*
 * File automatically generated by
 * gengen 1.0 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef PRINT_HELP_STRING_GEN_CLASS_H
#define PRINT_HELP_STRING_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class print_help_string_gen_class
{
 protected:
  string helpstring;

 public:
  print_help_string_gen_class()
  {
  }
  
  print_help_string_gen_class(const string &_helpstring) :
    helpstring (_helpstring)
  {
  }

  static void
  generate_string(const string &s, ostream &stream, unsigned int indent)
  {
    if (!indent || s.find('\n') == string::npos)
      {
        stream << s;
        return;
      }

    string::size_type pos;
    string::size_type start = 0;
    string ind (indent, ' ');
    while ( (pos=s.find('\n', start)) != string::npos)
      {
        stream << s.substr (start, (pos+1)-start);
        start = pos+1;
        if (start+1 <= s.size ())
          stream << ind;
      }
    if (start+1 <= s.size ())
      stream << s.substr (start);
  }

  void set_helpstring(const string &_helpstring)
  {
    helpstring = _helpstring;
  }

  void generate_print_help_string(ostream &stream, unsigned int indent = 0);
  
};

#endif // PRINT_HELP_STRING_GEN_CLASS_H
