/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef STRING_BUILDER_DECLARE_GEN_CLASS_H
#define STRING_BUILDER_DECLARE_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class string_builder_declare_gen_class
{
 protected:
  int num_allocable_parts;

 public:
  string_builder_declare_gen_class() :
    num_allocable_parts (0)
  {
  }
  
  string_builder_declare_gen_class(int _num_allocable_parts) :
    num_allocable_parts (_num_allocable_parts)
  {
  }

  void set_num_allocable_parts(int _num_allocable_parts)
  {
    num_allocable_parts = _num_allocable_parts;
  }

  void generate_string_builder_declare(ostream &stream, unsigned int indent = 0);
  
};

#endif // STRING_BUILDER_DECLARE_GEN_CLASS_H
