/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "string_builder_declare.h"

void
string_builder_declare_gen_class::generate_string_builder_declare(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  stream << "const char *string_builder_parts[";
  stream << num_allocable_parts;
  stream << "];";
  stream << "\n";
  stream << indent_str;
  stream << "unsigned int string_builder_size, string_builder_i;";
  stream << "\n";
  stream << indent_str;
}
