/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "string_builder_allocate.h"

void
string_builder_allocate_gen_class::generate_string_builder_allocate(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  if (( num_parts == 0 ))
    {
      stream << "\n";
      stream << indent_str;
      generate_string (target, stream, indent + indent_str.length ());
      if (is_target_array)
        {
          stream << "[";
          generate_string (target_index, stream, indent + indent_str.length ());
          stream << "]";
        }
      stream << " = \"\";";
      stream << "\n";
      stream << indent_str;
    }
  else
    {
      if (( num_parts == 1 ))
        {
          generate_string (target, stream, indent + indent_str.length ());
          if (is_target_array)
            {
              stream << "[";
              generate_string (target_index, stream, indent + indent_str.length ());
              stream << "]";
            }
          stream << " = (char *)malloc( strlen( string_builder_parts[ 0 ] ) + 1 );";
          stream << "\n";
          stream << indent_str;
        }
      else
        {
          stream << "for( string_builder_size = string_builder_i = 0; string_builder_i < ";
          stream << num_parts;
          stream << "; string_builder_i++ )";
          stream << "\n";
          stream << indent_str;
          stream << "     string_builder_size += strlen( string_builder_parts[ string_builder_i ] );";
          stream << "\n";
          stream << indent_str;
          generate_string (target, stream, indent + indent_str.length ());
          if (is_target_array)
            {
              stream << "[";
              generate_string (target_index, stream, indent + indent_str.length ());
              stream << "]";
            }
          stream << " = (char *)malloc( string_builder_size + 1 );";
          stream << "\n";
          stream << indent_str;
        }
    }
}
