/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef STRING_BUILDER_PREPARE_GEN_CLASS_H
#define STRING_BUILDER_PREPARE_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class string_builder_prepare_gen_class
{
 protected:
  bool gengetopt_localised;
  bool localised;
  int part_index;
  string value;

 public:
  string_builder_prepare_gen_class() :
    gengetopt_localised (false), localised (false), part_index (0)
  {
  }
  
  string_builder_prepare_gen_class(bool _gengetopt_localised, bool _localised, int _part_index, const string &_value) :
    gengetopt_localised (_gengetopt_localised), localised (_localised), part_index (_part_index), value (_value)
  {
  }

  static void
  generate_string(const string &s, ostream &stream, unsigned int indent)
  {
    if (!indent || s.find('\n') == string::npos)
      {
        stream << s;
        return;
      }

    string::size_type pos;
    string::size_type start = 0;
    string ind (indent, ' ');
    while ( (pos=s.find('\n', start)) != string::npos)
      {
        stream << s.substr (start, (pos+1)-start);
        start = pos+1;
        if (start+1 <= s.size ())
          stream << ind;
      }
    if (start+1 <= s.size ())
      stream << s.substr (start);
  }

  void set_gengetopt_localised(bool _gengetopt_localised)
  {
    gengetopt_localised = _gengetopt_localised;
  }

  void set_localised(bool _localised)
  {
    localised = _localised;
  }

  void set_part_index(int _part_index)
  {
    part_index = _part_index;
  }

  void set_value(const string &_value)
  {
    value = _value;
  }

  void generate_string_builder_prepare(ostream &stream, unsigned int indent = 0);
  
};

#endif // STRING_BUILDER_PREPARE_GEN_CLASS_H
