/* cmdline.h */

/* File autogenerated by gengetopt version 2.16-rc  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "gengetopt"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION VERSION
#endif

struct gengetopt_args_info
{
  char * input_arg;	/* input file (default std input).  */
  char * input_orig;	/* input file (default std input) original value given at command line.  */
  char * func_name_arg;	/* name of generated function (default='cmdline_parser').  */
  char * func_name_orig;	/* name of generated function original value given at command line.  */
  char * arg_struct_name_arg;	/* name of generated args info struct (default='gengetopt_args_info').  */
  char * arg_struct_name_orig;	/* name of generated args info struct original value given at command line.  */
  char * file_name_arg;	/* name of generated file (default='cmdline').  */
  char * file_name_orig;	/* name of generated file original value given at command line.  */
  char * c_extension_arg;	/* extension of c file (default='c').  */
  char * c_extension_orig;	/* extension of c file original value given at command line.  */
  char * header_extension_arg;	/* extension of header file (default='h').  */
  char * header_extension_orig;	/* extension of header file original value given at command line.  */
  char * unamed_opts_arg;	/* accept options without names (e.g., file names) (default='FILES').  */
  char * unamed_opts_orig;	/* accept options without names (e.g., file names) original value given at command line.  */
  int gen_version_flag;	/* put gengetopt version in the generated file (default=on).  */
  char * set_package_arg;	/* set the package name (override package defined in the .ggo file).  */
  char * set_package_orig;	/* set the package name (override package defined in the .ggo file) original value given at command line.  */
  char * set_version_arg;	/* set the version number (override version defined in the .ggo file).  */
  char * set_version_orig;	/* set the version number (override version defined in the .ggo file) original value given at command line.  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int input_given ;	/* Whether input was given.  */
  int func_name_given ;	/* Whether func-name was given.  */
  int arg_struct_name_given ;	/* Whether arg-struct-name was given.  */
  int file_name_given ;	/* Whether file-name was given.  */
  int c_extension_given ;	/* Whether c-extension was given.  */
  int header_extension_given ;	/* Whether header-extension was given.  */
  int long_help_given ;	/* Whether long-help was given.  */
  int unamed_opts_given ;	/* Whether unamed-opts was given.  */
  int no_handle_help_given ;	/* Whether no-handle-help was given.  */
  int no_handle_version_given ;	/* Whether no-handle-version was given.  */
  int no_handle_error_given ;	/* Whether no-handle-error was given.  */
  int gen_version_given ;	/* Whether gen-version was given.  */
  int conf_parser_given ;	/* Whether conf-parser was given.  */
  int set_package_given ;	/* Whether set-package was given.  */
  int set_version_given ;	/* Whether set-version was given.  */
  int show_help_given ;	/* Whether show-help was given.  */
  int show_full_help_given ;	/* Whether show-full-help was given.  */
  int show_version_given ;	/* Whether show-version was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);
int cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
